const goodFacilityResponse = [
  {
    HireDate: "2018-02-01",
    IsOwner: false,
    IsManager: true,
    Occupations: [],
    Name: "Seq Number test",
    Alias: "Cannabis Connection",
    DisplayName: "Cannabis Connection",
    CredentialedDate: "2017-12-11",
    SupportActivationDate: null,
    SupportExpirationDate: null,
    SupportLastPaidDate: null,
    FacilityType: {
      IsMedical: false,
      IsRetail: true,
      CanGrowPlants: false,
      CanTagPlantBatches: false,
      CanAssignRoomsToPlantBatches: false,
      CanTrackVegetativePlants: true,
      PlantsRequirePatientAffiliation: false,
      CanPackageVegetativePlants: false,
      CanReportHarvestSchedules: false,
      CanSubmitHarvestsForTesting: false,
      CanRequireHarvestSampleLabTestBatches: false,
      CanCreateOpeningBalancePackages: true,
      CanCreateDerivedPackages: true,
      CanAssignRoomsToPackages: false,
      PackagesRequirePatientAffiliation: false,
      CanSubmitPackagesForTesting: true,
      CanCreateProcessValidationPackages: false,
      CanRequirePackageSampleLabTestBatches: false,
      CanRequestProductRemediation: true,
      CanRemediatePackagesWithFailedLabResults: false,
      CanInfuseProducts: false,
      CanTestPackages: false,
      CanSellToConsumers: false,
      CanSellToPatients: false,
      CanSellToExternalPatients: false,
      CanSellToCaregivers: false,
      AdvancedSales: false,
      SalesRequirePatientNumber: false,
      SalesRequireExternalPatientNumber: false,
      SalesRequireExternalPatientIdentificationMethod: false,
      SalesRequireCaregiverNumber: false,
      SalesRequireCaregiverPatientNumber: false,
      CanDeliverSalesToConsumers: false,
      CanDeliverSalesToPatients: false,
      SalesDeliveryRequirePatientNumber: false,
      CanHaveMemberPatients: false,
      TotalMemberPatientsAllowed: null,
      CanReportPatientsAdverseResponses: false
    },
    License: {
      Number: "C11-0000090-LIC",
      StartDate: "2017-12-19",
      EndDate: "2019-01-01",
      LicenseType: "A-Type 11 Distributor"
    }
  },
  {
    HireDate: "2018-02-01",
    IsOwner: false,
    IsManager: true,
    Occupations: [],
    Name: "Cannabis Creations",
    Alias: null,
    DisplayName: "Cannabis Creations",
    CredentialedDate: "2017-12-11",
    SupportActivationDate: null,
    SupportExpirationDate: null,
    SupportLastPaidDate: null,
    FacilityType: {
      IsMedical: false,
      IsRetail: true,
      CanGrowPlants: false,
      CanTagPlantBatches: false,
      CanAssignRoomsToPlantBatches: false,
      CanTrackVegetativePlants: true,
      PlantsRequirePatientAffiliation: false,
      CanPackageVegetativePlants: false,
      CanReportHarvestSchedules: false,
      CanSubmitHarvestsForTesting: false,
      CanRequireHarvestSampleLabTestBatches: false,
      CanCreateOpeningBalancePackages: true,
      CanCreateDerivedPackages: true,
      CanAssignRoomsToPackages: false,
      PackagesRequirePatientAffiliation: false,
      CanSubmitPackagesForTesting: false,
      CanCreateProcessValidationPackages: false,
      CanRequirePackageSampleLabTestBatches: false,
      CanRequestProductRemediation: false,
      CanRemediatePackagesWithFailedLabResults: true,
      CanInfuseProducts: true,
      CanTestPackages: false,
      CanSellToConsumers: false,
      CanSellToPatients: false,
      CanSellToExternalPatients: false,
      CanSellToCaregivers: false,
      AdvancedSales: false,
      SalesRequirePatientNumber: false,
      SalesRequireExternalPatientNumber: false,
      SalesRequireExternalPatientIdentificationMethod: false,
      SalesRequireCaregiverNumber: false,
      SalesRequireCaregiverPatientNumber: false,
      CanDeliverSalesToConsumers: false,
      CanDeliverSalesToPatients: false,
      SalesDeliveryRequirePatientNumber: false,
      CanHaveMemberPatients: false,
      TotalMemberPatientsAllowed: null,
      CanReportPatientsAdverseResponses: false
    },
    License: {
      Number: "CDPH-0000003",
      StartDate: "2018-03-01",
      EndDate: "2019-02-28",
      LicenseType: "A-Type 6: Non Volatile Solvent Extraction"
    }
  },
  {
    HireDate: "2018-02-01",
    IsOwner: false,
    IsManager: true,
    Occupations: [],
    Name: "Cannabis Farms",
    Alias: null,
    DisplayName: "Cannabis Farms",
    CredentialedDate: "2017-12-11",
    SupportActivationDate: null,
    SupportExpirationDate: null,
    SupportLastPaidDate: null,
    FacilityType: {
      IsMedical: true,
      IsRetail: false,
      CanGrowPlants: true,
      CanTagPlantBatches: true,
      CanAssignRoomsToPlantBatches: true,
      CanTrackVegetativePlants: false,
      PlantsRequirePatientAffiliation: false,
      CanPackageVegetativePlants: true,
      CanReportHarvestSchedules: false,
      CanSubmitHarvestsForTesting: false,
      CanRequireHarvestSampleLabTestBatches: false,
      CanCreateOpeningBalancePackages: true,
      CanCreateDerivedPackages: true,
      CanAssignRoomsToPackages: false,
      PackagesRequirePatientAffiliation: false,
      CanSubmitPackagesForTesting: false,
      CanCreateProcessValidationPackages: false,
      CanRequirePackageSampleLabTestBatches: false,
      CanRequestProductRemediation: false,
      CanRemediatePackagesWithFailedLabResults: false,
      CanInfuseProducts: false,
      CanTestPackages: false,
      CanSellToConsumers: false,
      CanSellToPatients: false,
      CanSellToExternalPatients: false,
      CanSellToCaregivers: false,
      AdvancedSales: false,
      SalesRequirePatientNumber: false,
      SalesRequireExternalPatientNumber: false,
      SalesRequireExternalPatientIdentificationMethod: false,
      SalesRequireCaregiverNumber: false,
      SalesRequireCaregiverPatientNumber: false,
      CanDeliverSalesToConsumers: false,
      CanDeliverSalesToPatients: false,
      SalesDeliveryRequirePatientNumber: false,
      CanHaveMemberPatients: false,
      TotalMemberPatientsAllowed: null,
      CanReportPatientsAdverseResponses: false
    },
    License: {
      Number: "CML17-0000001",
      StartDate: "2018-01-01",
      EndDate: "2018-12-31",
      LicenseType: "M-Medium Mixed-Light Tier 2"
    }
  },
  {
    HireDate: "2018-02-01",
    IsOwner: false,
    IsManager: true,
    Occupations: [],
    Name: "Cannabis Microbusiness",
    Alias: null,
    DisplayName: "Cannabis Microbusiness",
    CredentialedDate: "2017-12-11",
    SupportActivationDate: null,
    SupportExpirationDate: null,
    SupportLastPaidDate: null,
    FacilityType: {
      IsMedical: false,
      IsRetail: true,
      CanGrowPlants: true,
      CanTagPlantBatches: true,
      CanAssignRoomsToPlantBatches: true,
      CanTrackVegetativePlants: false,
      PlantsRequirePatientAffiliation: false,
      CanPackageVegetativePlants: true,
      CanReportHarvestSchedules: false,
      CanSubmitHarvestsForTesting: false,
      CanRequireHarvestSampleLabTestBatches: false,
      CanCreateOpeningBalancePackages: true,
      CanCreateDerivedPackages: true,
      CanAssignRoomsToPackages: false,
      PackagesRequirePatientAffiliation: false,
      CanSubmitPackagesForTesting: true,
      CanCreateProcessValidationPackages: false,
      CanRequirePackageSampleLabTestBatches: false,
      CanRequestProductRemediation: true,
      CanRemediatePackagesWithFailedLabResults: true,
      CanInfuseProducts: true,
      CanTestPackages: false,
      CanSellToConsumers: true,
      CanSellToPatients: false,
      CanSellToExternalPatients: false,
      CanSellToCaregivers: false,
      AdvancedSales: true,
      SalesRequirePatientNumber: false,
      SalesRequireExternalPatientNumber: false,
      SalesRequireExternalPatientIdentificationMethod: false,
      SalesRequireCaregiverNumber: false,
      SalesRequireCaregiverPatientNumber: false,
      CanDeliverSalesToConsumers: false,
      CanDeliverSalesToPatients: false,
      SalesDeliveryRequirePatientNumber: false,
      CanHaveMemberPatients: false,
      TotalMemberPatientsAllowed: null,
      CanReportPatientsAdverseResponses: false
    },
    License: {
      Number: "A12-0000015-LIC",
      StartDate: "2018-08-01",
      EndDate: "2019-07-31",
      LicenseType: "A-Type 12 Microbusiness"
    }
  },
  {
    HireDate: "2018-02-01",
    IsOwner: false,
    IsManager: true,
    Occupations: [],
    Name: "Cannabis Processing",
    Alias: null,
    DisplayName: "Cannabis Processing",
    CredentialedDate: "2017-12-11",
    SupportActivationDate: null,
    SupportExpirationDate: null,
    SupportLastPaidDate: null,
    FacilityType: {
      IsMedical: false,
      IsRetail: true,
      CanGrowPlants: false,
      CanTagPlantBatches: false,
      CanAssignRoomsToPlantBatches: false,
      CanTrackVegetativePlants: true,
      PlantsRequirePatientAffiliation: false,
      CanPackageVegetativePlants: false,
      CanReportHarvestSchedules: false,
      CanSubmitHarvestsForTesting: false,
      CanRequireHarvestSampleLabTestBatches: false,
      CanCreateOpeningBalancePackages: true,
      CanCreateDerivedPackages: true,
      CanAssignRoomsToPackages: false,
      PackagesRequirePatientAffiliation: false,
      CanSubmitPackagesForTesting: false,
      CanCreateProcessValidationPackages: false,
      CanRequirePackageSampleLabTestBatches: false,
      CanRequestProductRemediation: false,
      CanRemediatePackagesWithFailedLabResults: false,
      CanInfuseProducts: false,
      CanTestPackages: false,
      CanSellToConsumers: false,
      CanSellToPatients: false,
      CanSellToExternalPatients: false,
      CanSellToCaregivers: false,
      AdvancedSales: false,
      SalesRequirePatientNumber: false,
      SalesRequireExternalPatientNumber: false,
      SalesRequireExternalPatientIdentificationMethod: false,
      SalesRequireCaregiverNumber: false,
      SalesRequireCaregiverPatientNumber: false,
      CanDeliverSalesToConsumers: false,
      CanDeliverSalesToPatients: false,
      SalesDeliveryRequirePatientNumber: false,
      CanHaveMemberPatients: false,
      TotalMemberPatientsAllowed: null,
      CanReportPatientsAdverseResponses: false
    },
    License: {
      Number: "CAL17-0000005",
      StartDate: "2018-02-01",
      EndDate: "2019-01-31",
      LicenseType: "A-Processor"
    }
  },
  {
    HireDate: "2018-02-01",
    IsOwner: false,
    IsManager: true,
    Occupations: [],
    Name: "Cannabis Sales",
    Alias: null,
    DisplayName: "Cannabis Sales",
    CredentialedDate: "2017-12-11",
    SupportActivationDate: null,
    SupportExpirationDate: null,
    SupportLastPaidDate: null,
    FacilityType: {
      IsMedical: true,
      IsRetail: false,
      CanGrowPlants: false,
      CanTagPlantBatches: false,
      CanAssignRoomsToPlantBatches: false,
      CanTrackVegetativePlants: true,
      PlantsRequirePatientAffiliation: false,
      CanPackageVegetativePlants: false,
      CanReportHarvestSchedules: false,
      CanSubmitHarvestsForTesting: false,
      CanRequireHarvestSampleLabTestBatches: false,
      CanCreateOpeningBalancePackages: true,
      CanCreateDerivedPackages: true,
      CanAssignRoomsToPackages: false,
      PackagesRequirePatientAffiliation: false,
      CanSubmitPackagesForTesting: false,
      CanCreateProcessValidationPackages: false,
      CanRequirePackageSampleLabTestBatches: false,
      CanRequestProductRemediation: false,
      CanRemediatePackagesWithFailedLabResults: false,
      CanInfuseProducts: false,
      CanTestPackages: false,
      CanSellToConsumers: false,
      CanSellToPatients: true,
      CanSellToExternalPatients: false,
      CanSellToCaregivers: true,
      AdvancedSales: true,
      SalesRequirePatientNumber: false,
      SalesRequireExternalPatientNumber: false,
      SalesRequireExternalPatientIdentificationMethod: false,
      SalesRequireCaregiverNumber: false,
      SalesRequireCaregiverPatientNumber: false,
      CanDeliverSalesToConsumers: false,
      CanDeliverSalesToPatients: false,
      SalesDeliveryRequirePatientNumber: false,
      CanHaveMemberPatients: false,
      TotalMemberPatientsAllowed: null,
      CanReportPatientsAdverseResponses: false
    },
    License: {
      Number: "M10-0000004-LIC",
      StartDate: "2018-07-01",
      EndDate: "2019-06-30",
      LicenseType: "M-Type 10 Retailer"
    }
  },
  {
    HireDate: "2018-02-01",
    IsOwner: false,
    IsManager: true,
    Occupations: [],
    Name: "Cannabis Science",
    Alias: null,
    DisplayName: "Cannabis Science",
    CredentialedDate: "2017-12-11",
    SupportActivationDate: null,
    SupportExpirationDate: null,
    SupportLastPaidDate: null,
    FacilityType: {
      IsMedical: true,
      IsRetail: true,
      CanGrowPlants: false,
      CanTagPlantBatches: false,
      CanAssignRoomsToPlantBatches: false,
      CanTrackVegetativePlants: true,
      PlantsRequirePatientAffiliation: false,
      CanPackageVegetativePlants: false,
      CanReportHarvestSchedules: false,
      CanSubmitHarvestsForTesting: false,
      CanRequireHarvestSampleLabTestBatches: false,
      CanCreateOpeningBalancePackages: true,
      CanCreateDerivedPackages: true,
      CanAssignRoomsToPackages: false,
      PackagesRequirePatientAffiliation: false,
      CanSubmitPackagesForTesting: false,
      CanCreateProcessValidationPackages: false,
      CanRequirePackageSampleLabTestBatches: false,
      CanRequestProductRemediation: false,
      CanRemediatePackagesWithFailedLabResults: false,
      CanInfuseProducts: false,
      CanTestPackages: true,
      CanSellToConsumers: false,
      CanSellToPatients: false,
      CanSellToExternalPatients: false,
      CanSellToCaregivers: false,
      AdvancedSales: false,
      SalesRequirePatientNumber: false,
      SalesRequireExternalPatientNumber: false,
      SalesRequireExternalPatientIdentificationMethod: false,
      SalesRequireCaregiverNumber: false,
      SalesRequireCaregiverPatientNumber: false,
      CanDeliverSalesToConsumers: false,
      CanDeliverSalesToPatients: false,
      SalesDeliveryRequirePatientNumber: false,
      CanHaveMemberPatients: false,
      TotalMemberPatientsAllowed: null,
      CanReportPatientsAdverseResponses: false
    },
    License: {
      Number: "008-0000010-LIC",
      StartDate: "2018-06-01",
      EndDate: "2019-05-31",
      LicenseType: "Type 8 Testing"
    }
  },
  {
    HireDate: "2018-02-01",
    IsOwner: false,
    IsManager: true,
    Occupations: [],
    Name: "Cannabis Transport",
    Alias: null,
    DisplayName: "Cannabis Transport",
    CredentialedDate: "2017-12-11",
    SupportActivationDate: null,
    SupportExpirationDate: null,
    SupportLastPaidDate: null,
    FacilityType: {
      IsMedical: false,
      IsRetail: true,
      CanGrowPlants: false,
      CanTagPlantBatches: false,
      CanAssignRoomsToPlantBatches: false,
      CanTrackVegetativePlants: true,
      PlantsRequirePatientAffiliation: false,
      CanPackageVegetativePlants: false,
      CanReportHarvestSchedules: false,
      CanSubmitHarvestsForTesting: false,
      CanRequireHarvestSampleLabTestBatches: false,
      CanCreateOpeningBalancePackages: false,
      CanCreateDerivedPackages: false,
      CanAssignRoomsToPackages: false,
      PackagesRequirePatientAffiliation: false,
      CanSubmitPackagesForTesting: false,
      CanCreateProcessValidationPackages: false,
      CanRequirePackageSampleLabTestBatches: false,
      CanRequestProductRemediation: false,
      CanRemediatePackagesWithFailedLabResults: false,
      CanInfuseProducts: false,
      CanTestPackages: false,
      CanSellToConsumers: false,
      CanSellToPatients: false,
      CanSellToExternalPatients: false,
      CanSellToCaregivers: false,
      AdvancedSales: false,
      SalesRequirePatientNumber: false,
      SalesRequireExternalPatientNumber: false,
      SalesRequireExternalPatientIdentificationMethod: false,
      SalesRequireCaregiverNumber: false,
      SalesRequireCaregiverPatientNumber: false,
      CanDeliverSalesToConsumers: false,
      CanDeliverSalesToPatients: false,
      SalesDeliveryRequirePatientNumber: false,
      CanHaveMemberPatients: false,
      TotalMemberPatientsAllowed: null,
      CanReportPatientsAdverseResponses: false
    },
    License: {
      Number: "C13-0000092-LIC",
      StartDate: "2018-04-01",
      EndDate: "2019-03-31",
      LicenseType: "A-Type 13 Distributor-Transport Only"
    }
  }
];

module.exports = {
  goodFacilityResponse
};
