const goodActiveHarvestResponse = [ { Id: 17402,
    Name: 'Sprout Harvest Zip',
    HarvestType: 'WholePlant',
    SourceStrainCount: 1,
    SourceStrainNames: 'Zip Sprout Kull',
    Strains: [],
    DryingRoomId: 25906,
    DryingRoomName: 'Harvest Room A55',
    PatientLicenseNumber: '',
    CurrentWeight: 90.13,
    TotalWasteWeight: 11.23,
    PlantCount: 1,
    TotalWetWeight: 101.36,
    TotalRestoredWeight: 0,
    PackageCount: 0,
    TotalPackagedWeight: 0,
    UnitOfWeightName: 'Grams',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: null,
    IsOnHold: false,
    HarvestStartDate: '2018-10-31',
    FinishedDate: null,
    ArchivedDate: null,
    LastModified: '2018-10-31T19:06:24-07:00' },
  { Id: 17401,
    Name: 'Sprout Harvest 99',
    HarvestType: 'Product',
    SourceStrainCount: 1,
    SourceStrainNames: 'Zip Sprout Kull',
    Strains: [],
    DryingRoomId: 25907,
    DryingRoomName: 'Planting Room 201',
    PatientLicenseNumber: '',
    CurrentWeight: -109.9,
    TotalWasteWeight: 0,
    PlantCount: 1,
    TotalWetWeight: 100.56,
    TotalRestoredWeight: 0,
    PackageCount: 2,
    TotalPackagedWeight: 210.46,
    UnitOfWeightName: 'Grams',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: null,
    IsOnHold: false,
    HarvestStartDate: '2018-10-31',
    FinishedDate: null,
    ArchivedDate: null,
    LastModified: '2018-10-31T21:11:16-07:00' } ]
const goodHarvestByIdResponse = { Id: 13801,
    Name: '2018-09-13_Spring Hill Kush_Encore Growing and Drying Room',
    HarvestType: 'WholePlant',
    SourceStrainCount: 1,
    SourceStrainNames: 'Spring Hill Kush',
    Strains: [],
    DryingRoomId: 20006,
    DryingRoomName: 'Encore Growing and Drying Room',
    PatientLicenseNumber: '',
    CurrentWeight: 1571.1,
    TotalWasteWeight: 36.9,
    PlantCount: 3,
    TotalWetWeight: 1608,
    TotalRestoredWeight: 0,
    PackageCount: 0,
    TotalPackagedWeight: 0,
    UnitOfWeightName: 'Grams',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: null,
    IsOnHold: false,
    HarvestStartDate: '2018-09-13',
    FinishedDate: null,
    ArchivedDate: null,
    LastModified: '2018-09-13T16:29:02-07:00' }


module.exports = {
    goodActiveHarvestResponse,
    goodHarvestByIdResponse
}