const goodActivePackageResponse = [
  {
    Id: 30801,
    Label: '1A4FF0300000029000000978',
    PackageType: 'Product',
    SourceHarvestNames: '',
    RoomId: null,
    RoomName: null,
    Quantity: 9.99,
    UnitOfMeasureName: 'Grams',
    UnitOfMeasureAbbreviation: 'g',
    PatientLicenseNumber: '',
    ProductId: 5603,
    ProductName: 'Rad Caps',
    ProductCategoryName: 'Other Concentrate (weight)',
    PackagedDate: '2018-11-01',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-11-01',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T08:09:49+00:00',
  },
  {
    Id: 30802,
    Label: '1A4FF0300000029000000979',
    PackageType: 'Product',
    SourceHarvestNames: '',
    RoomId: null,
    RoomName: null,
    Quantity: 90,
    UnitOfMeasureName: 'Grams',
    UnitOfMeasureAbbreviation: 'g',
    PatientLicenseNumber: '',
    ProductId: 5603,
    ProductName: 'Rad Caps',
    ProductCategoryName: 'Other Concentrate (weight)',
    PackagedDate: '2018-11-01',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-11-01',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T08:09:51+00:00',
  },
  {
    Id: 30803,
    Label: '1A4FF0300000029000000980',
    PackageType: 'Product',
    SourceHarvestNames: '',
    RoomId: null,
    RoomName: null,
    Quantity: 1,
    UnitOfMeasureName: 'Ounces',
    UnitOfMeasureAbbreviation: 'oz',
    PatientLicenseNumber: '',
    ProductId: 19901,
    ProductName: "Alexander's Flower",
    ProductCategoryName: 'Flower',
    PackagedDate: '2018-11-01',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-11-01',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T08:10:32+00:00',
  },
  {
    Id: 30804,
    Label: '1A4FF0300000029000000981',
    PackageType: 'Product',
    SourceHarvestNames: '',
    RoomId: null,
    RoomName: null,
    Quantity: 2,
    UnitOfMeasureName: 'Ounces',
    UnitOfMeasureAbbreviation: 'oz',
    PatientLicenseNumber: '',
    ProductId: 19901,
    ProductName: "Alexander's Flower",
    ProductCategoryName: 'Flower',
    PackagedDate: '2018-11-01',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-11-01',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T08:10:33+00:00',
  },
  {
    Id: 30805,
    Label: '1A4FF0300000029000000984',
    PackageType: 'Product',
    SourceHarvestNames: 'Harvest-783 2018-07-17',
    RoomId: null,
    RoomName: null,
    Quantity: 5,
    UnitOfMeasureName: 'Each',
    UnitOfMeasureAbbreviation: 'ea',
    PatientLicenseNumber: '',
    ProductId: 26203,
    ProductName: 'ezG Capsule Item 10',
    ProductCategoryName: 'Immature Plant',
    PackagedDate: '2018-11-01',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-11-01',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T08:13:32+00:00',
  },
  {
    Id: 30806,
    Label: '1A4FF0300000029000000987',
    PackageType: 'Product',
    SourceHarvestNames: '2018-07-27-Harvest Room-H',
    RoomId: null,
    RoomName: null,
    Quantity: 0.05,
    UnitOfMeasureName: 'Grams',
    UnitOfMeasureAbbreviation: 'g',
    PatientLicenseNumber: '',
    ProductId: 8301,
    ProductName: 'KP Product 59',
    ProductCategoryName: 'Edible (weight)',
    PackagedDate: '2018-11-01',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-11-01',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T10:28:46+00:00',
  },
  {
    Id: 28801,
    Label: '1A4FF0300000029000000952',
    PackageType: 'Product',
    SourceHarvestNames: '2018-07-27-Harvest Room-H',
    RoomId: null,
    RoomName: null,
    Quantity: 0.05,
    UnitOfMeasureName: 'Grams',
    UnitOfMeasureAbbreviation: 'g',
    PatientLicenseNumber: '',
    ProductId: 8301,
    ProductName: 'KP Product 59',
    ProductCategoryName: 'Edible (weight)',
    PackagedDate: '2018-10-26',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-10-26',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T10:28:46+00:00',
  },
  {
    Id: 27701,
    Label: '1A4FF0300000029000001082',
    PackageType: 'Product',
    SourceHarvestNames: '',
    RoomId: null,
    RoomName: null,
    Quantity: 1,
    UnitOfMeasureName: 'Ounces',
    UnitOfMeasureAbbreviation: 'oz',
    PatientLicenseNumber: '',
    ProductId: 19901,
    ProductName: "Alexander's Flower",
    ProductCategoryName: 'Flower',
    PackagedDate: '2018-10-16',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-10-16',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T08:10:33+00:00',
  },
  {
    Id: 30305,
    Label: '1A4FF0300000029000000965',
    PackageType: 'Product',
    SourceHarvestNames: '',
    RoomId: null,
    RoomName: null,
    Quantity: 900,
    UnitOfMeasureName: 'Grams',
    UnitOfMeasureAbbreviation: 'g',
    PatientLicenseNumber: 'X00001',
    ProductId: 5603,
    ProductName: 'Rad Caps',
    ProductCategoryName: 'Other Concentrate (weight)',
    PackagedDate: '2018-09-17',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-09-17',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T08:09:51+00:00',
  },
  {
    Id: 21401,
    Label: '1A4FF0300000029000000124',
    PackageType: 'Product',
    SourceHarvestNames: 'Harvest-783 2018-07-17',
    RoomId: null,
    RoomName: null,
    Quantity: -1367.7381,
    UnitOfMeasureName: 'Grams',
    UnitOfMeasureAbbreviation: 'g',
    PatientLicenseNumber: '',
    ProductId: 19201,
    ProductName: 'Cannobis Juice',
    ProductCategoryName: 'Other Concentrate (weight)',
    PackagedDate: '2018-07-18',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-07-18',
    IsProductionBatch: true,
    ProductionBatchNumber: '1CKW71-3',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T19:00:11+00:00',
  },
  {
    Id: 10502,
    Label: '1A4FF0300000029000000011',
    PackageType: 'Product',
    SourceHarvestNames: '2018-01-25-GH_DryingRoom-ca-1-M',
    RoomId: null,
    RoomName: null,
    Quantity: -46.31,
    UnitOfMeasureName: 'Grams',
    UnitOfMeasureAbbreviation: 'g',
    PatientLicenseNumber: '',
    ProductId: 5603,
    ProductName: 'Rad Caps',
    ProductCategoryName: 'Other Concentrate (weight)',
    PackagedDate: '2018-03-23',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2018-03-23',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T14:30:10+00:00',
  },
  {
    Id: 14602,
    Label: '1A4FF0300000029000000087',
    PackageType: 'Product',
    SourceHarvestNames: 'Veg Room 1 - 2018-04-07',
    RoomId: null,
    RoomName: null,
    Quantity: 70.23,
    UnitOfMeasureName: 'Grams',
    UnitOfMeasureAbbreviation: 'g',
    PatientLicenseNumber: '',
    ProductId: 11001,
    ProductName: 'Dauntless Buds',
    ProductCategoryName: 'Flower',
    PackagedDate: '2015-12-15',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2015-12-15',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T14:31:22+00:00',
  },
  {
    Id: 28222,
    Label: '1A4FF0300000029000000129',
    PackageType: 'Product',
    SourceHarvestNames: 'Harvest-783 2018-07-17',
    RoomId: null,
    RoomName: null,
    Quantity: 11,
    UnitOfMeasureName: 'Each',
    UnitOfMeasureAbbreviation: 'ea',
    PatientLicenseNumber: '',
    ProductId: 26203,
    ProductName: 'ezG Capsule Item 10',
    ProductCategoryName: 'Immature Plant',
    PackagedDate: '2015-12-15',
    InitialLabTestingState: 'NotSubmitted',
    LabTestingState: 'NotSubmitted',
    LabTestingStateDate: '2015-12-15',
    IsProductionBatch: false,
    ProductionBatchNumber: '',
    IsTestingSample: false,
    IsProcessValidationTestingSample: false,
    ProductRequiresRemediation: false,
    ContainsRemediatedProduct: false,
    RemediationDate: null,
    ReceivedFromManifestNumber: null,
    ReceivedFromFacilityLicenseNumber: null,
    ReceivedFromFacilityName: null,
    ReceivedDateTime: null,
    IsOnHold: false,
    ArchivedDate: null,
    FinishedDate: null,
    LastModified: '2018-11-01T08:13:32+00:00',
  },
];

module.exports = {
  goodActivePackageResponse,
};
